### ISSUE TITLE
After nuget update, "CloudConfigurationManager does not exist in current context" error appears

### ISSUE THREAD

**Issue by btakeya** [o-hoo/Around#9] opened 2015-08-10 14:06 UTC
@ 98e2f76f

**Comment by btakeya** [comment] 2015-08-10 14:10
@modamoda does it also happened on Windows?

**Comment by modamoda** [comment] 2015-08-16 10:27
It was caused by legacy dependent libraries.
-> resolved by committing kstreee-around/AroundServer@e94aaec73b2a3245135cc21c85a4aaf550acbb3c

**Closed as completed by modamoda** 2015-08-16 10:27 UTC
Labels: 1. Server, 2. Bug
